trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    persistCredentials: true

  - task: UseNode@1
    inputs:
      version: '10.x'

  - script: |
      node scripts/script
    displayName: 'Check diff'
  
  - powershell: |
      $message = Get-Content -Path check.log -Raw
      Write-Host "##vso[task.setvariable variable=message]$message"
    displayName: 'Read log file'

  - powershell: |
      $contentType = "application/json; charset=utf-8";
      $headers = @{ Authorization = 'Bearer $(System.AccessToken)' };
      $rawRequest = @{comments = @(@{ parentCommentId = 0; content = "$(message)"; commentType = 1}); status = 1 };
      $request = ConvertTo-Json -Depth 3 $rawRequest;
      $uri = "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(System.PullRequest.PullRequestId)/threads/?api-version=7.2-preview.1";
      Invoke-RestMethod -Uri $uri -Method POST -Headers $headers -ContentType $contentType -Body $request;
